controller.B.onEvent(ControllerButtonEvent.Pressed, function () {
	 
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
	
})
function setUpBackground () {
	
}
function setUpPlayer () {
    mySprite = sprites.create(img`
        ......ffff..............
        ....fff22fff............
        ...fff2222fff...........
        ..fffeeeeeefff..........
        ..ffe222222eef..........
        ..fe2ffffff2ef..........
        ..ffffeeeeffff......ccc.
        .ffefbf44fbfeff....cddc.
        .ffefbf44fbfeff...cddc..
        .fee4dddddd4eef.ccddc...
        fdfeeddddd4eeffecddc....
        fbffee4444ee4fddccc.....
        fbf4f222222f1edde.......
        fcf.f222222f44ee........
        .ff.f445544f............
        ....ffffffff............
        .....ff..ff.............
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `, SpriteKind.Player)
    controller.player1.moveSprite(mySprite, 100, 100)
    mySprite.ay = 20
    mySprite.setStayInScreen(true)
}
let mySprite: Sprite = null
setUpPlayer()
setUpBackground()
forever(function () {
	
})
